### ISSUE TITLE
Android crash when update to V6.1.3

### ISSUE THREAD

**Issue by haivieted** [mieszko4/react-native-zoom-us#116]
App cannot start when i update to react-native-zoom-us Ver 6.1.3
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/drm/DefaultDrmSessionEventListener;

**Comment by mieszko4** [comment]
Have you followed the upgrade guide - https://github.com/mieszko4/react-native-zoom-us/blob/master/docs/UPGRADING.md#600-jitpack

Also available here: https://github.com/mieszko4/react-native-zoom-us#installation

**Comment by haivieted** [comment]
Thank Mieszko4, it work.
